install.packages(
  pkgs = c("shinyjs", 
           "shinyWidgets", 
           "shinybusy", 
           "shinycssloaders", 
           "sass", 
           "jsonlite", 
           "readr", 
           "stringr", 
           "ggplot2", 
           "Cairo", 
           "data.table", 
           "lubridate", 
           "forcats", 
           "tidyr", 
           "magrittr", 
           "dplyr",
           "DBI",
           "RMySQL",
           "pool",
           "dbplyr",
           "sodium"
  ),
  repos = 'https://cran.rstudio.com/'
)
